export type ActionType =
  'CALL_WAMP_PROCEDURE' |
  'CONNECT_TO_WAMP_ROUTER' |
  'CONNECT_TO_WS_SERVER' |
  'DELETE_WAMP_CONNECTION' |
  'DELETE_WAMP_TOPIC_SUBSCRIPTION' |
  'DELETE_WS_CONNECTION' |
  'DISCONNECT_FROM_WAMP_ROUTER' |
  'DISCONNECT_FROM_WS_SERVER' |
  'EDIT_WAMP_CALL_FORM' |
  'EDIT_WAMP_CONNECTION_FORM' |
  'EDIT_WAMP_SUBSCRIPTION_FORM' |
  'EDIT_WS_CONNECTION_FORM' |
  'EDIT_WS_MESSAGE_FORM' |
  'HANDLE_WAMP_CONNECTION_CLOSED' |
  'HANDLE_WAMP_ERROR' |
  'HANDLE_WAMP_TOPIC_EVENT' |
  'HANDLE_WS_CONNECTION_CLOSED' |
  'HANDLE_WS_MESSAGE' |
  'HIDE_EVENT_DETAILS' |
  'LOAD_SAVED_STATE' |
  'SEND_WS_MESSAGE' |
  'SHOW_EVENT_DETAILS' |
  'SUBSCRIBE_TO_WAMP_TOPIC' |
  'UNSUBSCRIBE_FROM_WAMP_TOPIC'
;