export type ActionType =
  'CONNECT_TO_WAMP_ROUTER' |
  'DELETE_WAMP_TOPIC_SUBSCRIPTION' |
  'DISCONNECT_FROM_WAMP_ROUTER' |
  'EDIT_WAMP_CONNECTION_FORM' |
  'EDIT_WAMP_SUBSCRIPTION_FORM' |
  'HANDLE_WAMP_CONNECTION_CLOSED' |
  'HANDLE_WAMP_ERROR' |
  'HANDLE_WAMP_TOPIC_EVENT' |
  'LOAD_SAVED_STATE' |
  'SUBMIT_WAMP_CONNECTION_FORM' |
  'SUBMIT_WAMP_SUBSCRIPTION_FORM' |
  'SUBSCRIBE_TO_WAMP_TOPIC' |
  'UNSUBSCRIBE_FROM_WAMP_TOPIC'
;