export type ActionType =
  'CONNECT_TO_WAMP_ROUTER' |
  'DISCONNECT_FROM_WAMP_ROUTER' |
  'EDIT_WAMP_CONNECTION_FORM' |
  'HANDLE_WAMP_CONNECTION_CLOSED' |
  'LOAD_SAVED_STATE' |
  'SUBMIT_WAMP_CONNECTION_FORM'
;